# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_USER:
        ROLE_ADMIN: ROLE_USER #(access back-office)

    providers:
        in_memory:
            memory: ~
        app_user_provider:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticator:
                    - App\Security\LoginFormAuthenticator
            provider: app_user_provider
            logout:
                path: logout
            switch_user: ~

    access_control:
        - { path: ^/TheNinthDoor, role: ROLE_ADMIN }