vich_uploader:
    db_driver: orm
    mappings:
        Media:
            uri_prefix:         '%env(APP_PATH_MEDIA)%'
            upload_destination: '%kernel.project_dir%/public/%env(APP_PATH_MEDIA)%'
            namer:
                service: vich_uploader.namer_origname
        Merch:
            uri_prefix:         '%env(APP_PATH_MERCH)%'
            upload_destination: '%kernel.project_dir%/public/%env(APP_PATH_MERCH)%'
            namer:
                service: vich_uploader.namer_origname
        Sponsor:
            uri_prefix:         '%env(APP_PATH_SPONSORS)%'
            upload_destination: '%kernel.project_dir%/public/%env(APP_PATH_SPONSORS)%'
            namer:
                service: vich_uploader.namer_origname